export const video_categories = [
    'Amateur', 'Fetish', 'Hairy',
    'HD', 'Shower', 'Solo Female',
    'Anal', 'Big Ass', 'Fisting',
    'POV', 'Chubby', 'Creampie',
    'Brunette', 'Indian', 'Lesbian',
    'Outdoor', 'Tattoo', 'Big Tits',
    'Foot Fetish', 'Cum In Mouth', 'Mature',
    'Facial', 'Handjob', 'BBW',
    'Big Cock', 'Deepthroat', 'Rimming',
    'Group Sex', 'Cunnilingus', 'Teens (18+)',
    'Red Head', 'Toys', 'MILF',
    'Step Fantasy', 'Stockings', 'Pissing',
    'Blowjob', 'Doggystyle', 'Old and Young 18+',
    'Latex', 'Gangbang', 'Teacher',
    'Blonde', 'Couple', 'Lingerie',
    'Skinny', 'Threesome', 'Cuckold',
    'Masturbation', 'Big Nipples', 'Massage',
    'Interracial', 'Pregnant', 'Voyeur (fake)'
]