export const sub_categories = [
    { name: "Bangladeshi", count: 65 },
    { name: "Car", count: 134 },
    { name: "Changing Room", count: 7 },
    { name: "Close-up", count: 61 },
    { name: "Exhibitionism", count: 1 },
    { name: "Face Sitting", count: 44 },
    { name: "Fisting", count: 143 },
    { name: "Footjob", count: 159 },
    { name: "Gaping", count: 56 },
    { name: "Granny", count: 18 },
    { name: "Humiliation", count: 10 },
    { name: "Lactating", count: 142 },
    { name: "Latex", count: 29 },
    { name: "Masturbation", count: 142 },
    { name: "Mistress", count: 26 },
    { name: "Muscular Man", count: 33 },
    { name: "Nudist", count: 10 },
    { name: "Pakistani", count: 12 },
    { name: "Piercing", count: 7 },
    { name: "Pregnant", count: 231 },
    { name: "Public", count: 22 },
    { name: "Secretary", count: 37 },
    { name: "Shaved", count: 20 },
    { name: "Smoking", count: 104 },
    { name: "Spandex", count: 1 },
    { name: "Spanking", count: 69 },
    { name: "Squirt", count: 79 },
    { name: "Sri Lankan", count: 27 },
    { name: "Strapon", count: 102 },
    { name: "Striptease", count: 275 },
    { name: "Swallow Cum", count: 207 },
    { name: "Swingers", count: 4 },
    { name: "Tight Clothes", count: 1 },
    { name: "Twerk", count: 7 },
    { name: "Upskirt", count: 34 }
];

