// this is to remove stories that contains following keys for exoclick ads
export const BannedKeywords = [
    "abuse",
    "asphyxia",
    "behead",
    "bleed",
    "blood",
    "child",
    "children",
    "choke",
    "choking",
    "decapitation",
    "drugged",
    "forced",
    "kid",
    "kill",
    "loli",
    "murder",
    "rape",
    "shota",
    "snuff",
    "strangle",
    "torture",
    "family",
    "mom",
    "sister",
    "brother",
    "father",
    "maa",
    "mommy",
    "bhabhi",
    "aunty"

];
